In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

load /home/rl/scripts/karl/pairwise_interaction_experiments/20260630/Full_384_strain_collection_no_seq_info.csv and /home/rl/scripts/karl/pairwise_interaction_experiments/20260630/map_10_4_xgb.csv then do an inner join on Strain.Number and strain

In [4]:
# load and inner-join the two CSVs on Strain.Number (left) and strain (right)
path_full = "/home/rl/scripts/karl/pairwise_interaction_experiments/20260630/Full_384_strain_collection_no_seq_info.csv"
path_map = "/home/rl/scripts/karl/pairwise_interaction_experiments/20260630/map_10_4_xgb.csv"

df_full = pd.read_csv(path_full, dtype=str)
df_map = pd.read_csv(path_map, dtype=str)

# normalize keys
df_full['Strain.Number'] = df_full['Strain.Number'].str.strip()
df_map['strain'] = df_map['strain'].str.strip()

# inner join

df_merged = df_full.merge(df_map, left_on='Strain.Number', right_on='strain', how='inner')

print(f"full: {df_full.shape}, map: {df_map.shape}, merged: {df_merged.shape}")
df_merged.head()
display(df_merged)
df_merged.to_csv("/home/rl/scripts/karl/pairwise_interaction_experiments/20260630/strain_pool.csv", index=False)
print("Saved merged dataframe to strain_pool.csv")

full: (384, 7), map: (100, 2), merged: (100, 9)

,Well.position,Strain.Number,Well.number,Well,Schulenberg_strain_name,duplicated,*Some strain occur in more than one well,Strain_ID,strain
0,A1,1,1,A,NaN,no,NaN,1,1
1,A2,2,2,A,NaN,no,NaN,67,2
2,A6,12,6,A,NaN,no,NaN,14,12
3,A8,16,8,A,NaN,no,NaN,39,16
4,A10,18,10,A,NaN,no,NaN,51,18
...,...,...,...,...,...,...,...,...,...
95,P15,128,15,P,NaN,no,NaN,18,128
96,P17,132,17,P,NaN,no,NaN,22,132
97,P19,134,19,P,NaN,no,NaN,23,134
98,P21,136,21,P,NaN,no,NaN,24,136
99,P23,144,23,P,NaN,no,NaN,28,144

Saved merged dataframe to strain_pool.csv

In [11]:
#print unique values from well positions in the merged dataframe
print("Unique well positions in merged dataframe:")
print(df_merged['Well.position'].unique())
print(len(df_merged['Well.position'].unique()))

Unique well positions in merged dataframe:
['A1' 'A2' 'A6' 'A8' 'A10' 'A11' 'A12' 'A14' 'A15' 'A21' 'C14' 'C20' 'C22'
 'C24' 'D23' 'E2' 'E4' 'E5' 'E6' 'E7' 'E8' 'E9' 'E10' 'E12' 'E13' 'E14'
 'E15' 'E16' 'E18' 'E20' 'E21' 'E22' 'E24' 'F5' 'F7' 'F13' 'F15' 'F17'
 'F19' 'F21' 'F23' 'G1' 'G2' 'G3' 'G4' 'G5' 'G6' 'G7' 'G8' 'G9' 'G10'
 'G11' 'G12' 'G13' 'G14' 'G15' 'G17' 'G18' 'G19' 'G20' 'G21' 'G22' 'G23'
 'H5' 'H7' 'H11' 'H15' 'H17' 'H19' 'H23' 'I3' 'I9' 'I11' 'J1' 'J3' 'J5'
 'J9' 'J11' 'J13' 'M9' 'M11' 'M13' 'M17' 'M19' 'M21' 'O3' 'O7' 'O9' 'O11'
 'O13' 'O15' 'O17' 'O19' 'O21' 'P11' 'P15' 'P17' 'P19' 'P21' 'P23']
100

In [10]:
pick_df = pd.read_csv("/home/rl/scripts/karl/pairwise_interaction_experiments/20260630/picklist_Plate5(3).csv")
display(pick_df)
print("Unique well positions in picklist:")
print(pick_df['Source Well'].unique())
print(len(pick_df['Source Well'].unique()))

     Source Well  Transfer Volume (nL) Destination Well
0            G20                 600.0               A2
1             J9                 600.0               A2
2            F23                 600.0               A3
3            M21                 600.0               A3
4             G9                 600.0               A4
...          ...                   ...              ...
5203          A2                  75.0              P23
5204         H17                  75.0              P23
5205         H19                  75.0              P23
5206         O11                  75.0              P23
5207         O13                  75.0              P23

[5208 rows x 3 columns]

Unique well positions in picklist:
['G20' 'J9' 'F23' 'M21' 'G9' 'O11' 'E13' 'E20' 'P17' 'O15' 'H19' 'O19'
 'E10' 'A6' 'E12' 'H5' 'H7' 'E14' 'H17' 'M11' 'O3' 'E15' 'E18' 'E22' 'O13'
 'G21' 'P23' 'I9' 'P11' 'A2' 'A21' 'G4' 'G14' 'E8' 'E21' 'C24' 'A12' 'P15'
 'M13' 'A1' 'E16' 'P19' 'A11' 'G19' 'E5' 'J1' 'C22' 'J11' 'F5' 'G11' 'H23'
 'H11' 'C14' 'F13' 'G3' 'O9' 'C20' 'G18' 'I11' 'E6' 'M19' 'A14' 'E24'
 'P21' 'G22' 'A10' 'E7' 'G12' 'G5' 'F19' 'F21' 'G23' 'J3' 'M17' 'F15'
 'G15' 'G1' 'A15' 'O21' 'O17' 'I3' 'E9' 'A8' 'M9' 'G7' 'G17' 'G8' 'D23'
 'G13' 'G2' 'J13' 'J5' 'G10' 'E4' 'E2' 'G6' 'F7' 'H15' 'F17' 'O7']
100

In [12]:
#overlap between unique well positions in merged dataframe and picklist
merged_wells = set(df_merged['Well.position'].unique())
picklist_wells = set(pick_df['Source Well'].unique())
overlap = merged_wells.intersection(picklist_wells)
print(f"Overlap between merged dataframe and picklist: {len(overlap)} wells")

Overlap between merged dataframe and picklist: 100 wells

In [19]:
## create a function that reads in 96 well format data from the plate reader
def read_plate_reader_csv(file_path, n_headers=7):
    with open (file_path, 'r', encoding='cp1252') as f:
        lines = f.readlines()
    for i in range(n_headers):
        lines.pop(0)
    dataframe_lines = []
    #get a list of capital letters A-Z for the row labels
    letters = [chr(i) for i in range(65, 91)]
    cycle = 0
    time = 0
    t = 0
    row_number = 0
    for line in lines:
        if line.startswith("Cycle"):
            #to int
            cycle = int(line.split(':')[1].strip())
            row_number = 0 #reset rows
        elif line.startswith("Time"):
            time = int(line.split(':')[1].strip())
        elif line.startswith("T"):
            t = float(line.split(':')[1].strip())
        else:
            #assume this is a data line, split by commas
            data = line.strip().split(',')
            for i in range(len(data)):
                dataframe_line = [cycle, time, t, letters[row_number], i+1, data[i]]
                dataframe_lines.append(dataframe_line)
            row_number += 1
    #create a dataframe from the list of lists
    df = pd.DataFrame(dataframe_lines, columns=['Cycle', 'Time', 'T', 'Row', 'Column', 'Value'])
    return df

In [ ]:
dfa = read_plate_reader_csv("/home/rl/scripts/karl/pairwise_interaction_experiments/20260630/strain_check/Karl_20260630_111648_OD600_6m.csv")
dfa = dfa.drop(dfa[dfa['Cycle']==1].index) #drop cycle 1
dfb = read_plate_reader_csv("/home/rl/scripts/karl/pairwise_interaction_experiments/20260630/strain_check/Karl_20260630_113201_OD600_6m.csv")

display(dfa)

     Cycle  Time     T Row  Column   Value
96       2   180  30.4   A       1   1.185
97       2   180  30.4   A       2   1.143
98       2   180  30.4   A       3   1.659
99       2   180  30.4   A       4   1.071
100      2   180  30.4   A       5   1.241
..     ...   ...   ...  ..     ...     ...
187      2   180  30.4   H       8   1.276
188      2   180  30.4   H       9   1.152
189      2   180  30.4   H      10   0.982
190      2   180  30.4   H      11   1.059
191      2   180  30.4   H      12   0.302

[96 rows x 6 columns]